version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume-extractor
    restart: unless-stopped
    init: true
    environment:
      - DISPLAY=host.docker.internal:0.0
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

